export default {
  //Scroll Index
  SET_SCROLL_INDEX: "SET_SCROLL_INDEX",

  //Movie Category
  // Popular Movie Data
  SET_POPULAR_MOVIE_REQUEST: "SET_POPULAR_MOVIE_REQUEST",
  SET_POPULAR_MOVIE_SUCCESS: "SET_POPULAR_MOVIE_SUCCESS",
  SET_POPULAR_MOVIE_FAILURE: "SET_POPULAR_MOVIE_FAILURE",
  // NowPlaying Movie Data
  SET_NOWPLAYING_MOVIE_REQUEST: "SET_NOWPLAYING_MOVIE_REQUEST",
  SET_NOWPLAYING_MOVIE_SUCCESS: "SET_NOWPLAYING_MOVIE_SUCCESS",
  SET_NOWPLAYING_MOVIE_FAILURE: "SET_NOWPLAYING_MOVIE_FAILURE",
  // Upcoming Movie Data
  SET_UPCOMING_MOVIE_REQUEST: "SET_UPCOMING_MOVIE_REQUEST",
  SET_UPCOMING_MOVIE_SUCCESS: "SET_UPCOMING_MOVIE_SUCCESS",
  SET_UPCOMING_MOVIE_FAILURE: "SET_UPCOMING_MOVIE_FAILURE",
  // Toprated Movie Data
  SET_TOPRATED_MOVIE_REQUEST: "SET_TOPRATED_MOVIE_REQUEST",
  SET_TOPRATED_MOVIE_SUCCESS: "SET_TOPRATED_MOVIE_SUCCESS",
  SET_TOPRATED_MOVIE_FAILURE: "SET_TOPRATED_MOVIE_FAILURE",

  //TvShow Category
  // Popular Tvshow Data
  SET_POPULAR_TVSHOW_REQUEST: "SET_POPULAR_TVSHOW_REQUEST",
  SET_POPULAR_TVSHOW_SUCCESS: "SET_POPULAR_TVSHOW_SUCCESS",
  SET_POPULAR_TVSHOW_FAILURE: "SET_POPULAR_TVSHOW_FAILURE",
  // Airing Today Tvshow Data
  SET_AIRING_TODAY_TVSHOW_REQUEST: "SET_PAIRING_TODAY_TVSHOW_REQUEST",
  SET_AIRING_TODAY_TVSHOW_SUCCESS: "SET_PAIRING_TODAY_TVSHOW_SUCCESS",
  SET_AIRING_TODAY_TVSHOW_FAILURE: "SET_PAIRING_TODAY_TVSHOW_FAILURE",
  // On Tv Tvshow Data
  SET_ONTV_TVSHOW_REQUEST: "SET_ONTV_TVSHOW_REQUEST",
  SET_ONTV_TVSHOW_SUCCESS: "SET_ONTV_TVSHOW_SUCCESS",
  SET_ONTV_TVSHOW_FAILURE: "SET_ONTV_TVSHOW_FAILURE",
  // Toprated Tvshow Data
  SET_TOPRATED_TVSHOW_REQUEST: "SET_TOPRATED_TVSHOW_REQUEST",
  SET_TOPRATED_TVSHOW_SUCCESS: "SET_TOPRATED_TVSHOW_SUCCESS",
  SET_TOPRATED_TVSHOW_FAILURE: "SET_TOPRATED_TVSHOW_FAILURE",
}
