export default {
  //Reset Store
  SET_RESET_STORE: "SET_RESET_STORE",
  //fetch api call
  FETCH_API_CALL: "FETCH_API_CALL",
  //Scroll Index
  SET_SCROLL_INDEX: "SET_SCROLL_INDEX",
  // Popular Movie Data
  SET_POPULAR_MOVIE_DATA: "SET_POPULAR_MOVIE_DATA",
  // NowPlaying Movie Data
  SET_NOWPLAYING_MOVIE_DATA: "SET_NOWPLAYING_MOVIE_DATA",
  // Upcoming Movie Data
  SET_UPCOMING_MOVIE_DATA: "SET_UPCOMING_MOVIE_DATA",
  // Toprated Movie Data
  SET_TOPRATED_MOVIE_DATA: "SET_TOPRATED_MOVIE_DATA",
  // Popular Tvshow Data
  SET_POPULAR_TVSHOW_DATA: "SET_POPULAR_TVSHOW_DATA",
  // Airing Today Tvshow Data
  SET_AIRING_TODAY_TVSHOW_DATA: "SET_AIRING_TODAY_TVSHOW_DATA",
  // On Tv Tvshow Data
  SET_ONTV_TVSHOW_DATA: "SET_ONTV_TVSHOW_DATA",
  // Toprated Tvshow Data
  SET_TOPRATED_TVSHOW_DATA: "SET_TOPRATED_TVSHOW_DATA",
}
